name: nheko
version: 0.1.0
summary: Desktop client for the Matrix protocol
description: |
  The motivation behind the project is to provide a native desktop app for
  Matrix that feels more like a mainstream chat app (Riot, Telegram etc) and
  less like an IRC client.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  nheko:
    command: desktop-launch $SNAP/nheko
    plugs: [network, network-bind, x11, unity7, home]

parts:
  nheko:
    source: .
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DBUILD_TESTS=OFF
    build-packages:
      - gcc
      - g++
      - liblmdb-dev
      - liblmdb0
      - qttools5-dev-tools
    artifacts: [nheko]
    after: [desktop-qt5]
